name: Main Workflow

on:
  push:
    branches: [ main ]
  
jobs:
  Build:
    runs-on: ubuntu-latest
    container: gradle:6-jdk11
    steps:
      - name: Clone down repository
        uses: actions/checkout@v5
        
      - name: Build the application
        run: ci/build-app.sh

      - name: Run unit tests
        run: ci/unit-test-app.sh

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: code
          path: .
          include-hidden-files: true

  Lint:
    runs-on: ubuntu-latest
    needs: [ Build ]
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v5
        with:
          name: code
          path: .
          
      - name: Run linter
        uses: super-linter/super-linter/slim@v8
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
